package au.gov.nsw.records.digitalarchive.opengov.data;

// Generated Aug 29, 2012 1:21:11 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * TempList generated by hbm2java
 */
public class TempList implements java.io.Serializable {

	private Integer tempListId;
	private String name;
	private Set<Agency> agencies = new HashSet<Agency>(0);

	public TempList() {
	}

	public TempList(String name, Set<Agency> agencies) {
		this.name = name;
		this.agencies = agencies;
	}

	public Integer getTempListId() {
		return this.tempListId;
	}

	public void setTempListId(Integer tempListId) {
		this.tempListId = tempListId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set<Agency> getAgencies() {
		return this.agencies;
	}

	public void setAgencies(Set<Agency> agencies) {
		this.agencies = agencies;
	}

}
